import { createContext, useContext } from "react";

export type UiLanguage = "ko" | "en";

export type UiStrings = Record<string, string>;

export const uiStrings: Record<UiLanguage, UiStrings> = {
  ko: {
    add: "추가",
    library: "라이브러리",
    settings: "설정",
    openOutline: "목차 열기",
    closeOutline: "목차 닫기",
    resizeOutline: "목차 너비 조절",
    gridView: "그리드 보기",
    outlineView: "목차 보기",
    pageGrid: "페이지 그리드",
    documentInfo: "문서 정보",
    search: "검색",
    searchPrompt: "검색어를 입력하세요.",
    zoom: "확대/축소",
    zoomOut: "축소",
    zoomIn: "확대",
    page: "페이지",
    pages: "페이지",
    noDocument: "문서 없음",
    untitledPaper: "제목 없는 논문",
    aiOutline: "AI 목차",
    aiOutlinePending: "AI 목차 생성 중",
    autoHighlight: "자동 하이라이트",
    autoHighlightCompact: "오토하이라이트",
    autoHighlightToggle: "오토 하이라이트 켜기 끄기",
    autoHighlightCurrentPageOnly: "ON이어도 현재 페이지만 자동 하이라이트합니다.",
    autoHighlightCurrentPage: "현재 페이지 하이라이트",
    autoHighlightCurrentPageSetting: "현재 페이지만 자동 하이라이트",
    explainImage: "이미지 설명",
    imageExplanation: "이미지 설명",
    autoTranslate: "자동 번역",
    translatePage: "번역 실행",
    translationPanel: "번역창",
    openTranslationPanel: "번역창 열기",
    closeTranslationPanel: "번역창 닫기",
    shareTranslatedPdf: "번역 PDF 공유",
    addPdf: "PDF 추가",
    more: "더보기",
    panel: "패널",
    working: "작업 중",
    settingsTitle: "설정",
    settingsSubtitle: "UI 언어, 번역 언어, AI 에이전트, 화면 표시를 관리합니다.",
    uiLanguage: "UI 언어",
    translationLanguage: "번역 언어",
    theme: "테마",
    fontSize: "글자 크기",
    mathDelimiter: "수식 구분자",
    aiProvider: "AI 제공자",
    model: "모델",
    providerDefault: "제공자 기본값",
    bridgePath: "에이전트 큐 경로",
    customPrompt: "추가 프롬프트",
    runtimeHint: "AI 작업은 outbox/inbox JSON 큐로 처리되며, Codex CLI 또는 Claude Code가 로컬 작업을 수행합니다.",
    resetTitle: "라이브러리 전체 삭제",
    resetDescription: "가져온 PDF, 추출 텍스트, 하이라이트, 주석, 노트, AI 결과, 인용 카드, 에이전트 로그를 모두 삭제합니다.",
    resetAction: "라이브러리 전체 삭제",
    auto: "자동",
    refreshTranslation: "번역 새로고침",
    emptyTranslation: "PDF 텍스트를 읽는 중입니다. 문장이 추출되면 번역을 자동으로 요청합니다.",
    translationPending: "번역을 가져오는 중입니다...",
    translationMissing: "아직 번역이 없습니다. 새로고침을 누르면 이 문장 단위 번역을 요청합니다.",
    agentPending: "에이전트 응답 대기 중",
    keywordsDict: "키워드 사전",
    threeLineSummary: "3줄 요약",
    summary: "요약",
    keywordsEmpty: "AI 결과가 들어오면 핵심 키워드를 자동으로 정리합니다.",
    threeLineEmpty: "3줄 요약을 실행하면 여기에 정리됩니다.",
    summaryEmpty: "요약 또는 질문 답변 결과가 여기에 표시됩니다.",
    explain: "설명",
    translate: "번역",
    askAi: "AI에게 질문",
    citationReason: "인용 이유",
    linkSummary: "링크 요약",
    documentOutline: "문서 개요",
    paperRecommendations: "논문 추천",
    text: "텍스트",
    image: "이미지",
    url: "URL",
    table: "표",
    formula: "수식",
    activity: "활동",
    citations: "인용",
    notes: "주석",
    info: "정보",
    aiPendingAnswer: "에이전트 답변을 가져오는 중입니다.",
    noAnswerContent: "표시할 답변 내용이 없습니다.",
    pageTranslationFallback: "이 페이지의 텍스트를 렌더링한 뒤 자동 번역을 실행하면 번역 결과가 여기에 표시됩니다.",
    translationQueued: "번역 대기 중입니다.",
    translationMissingSaved: "아직 저장된 번역이 없습니다.",
    shareTruncated: "번역이 길어 일부 문장은 잘릴 수 있습니다.",
    noSentencesOnPage: "이 페이지에서 추출된 문장이 없습니다.",
    addPdfDrop: "클릭하거나 PDF를 이 화면으로 끌어오세요.",
    addPdfToSelectedFolder: "선택한 폴더에 논문을 추가합니다.",
    newFolder: "새 폴더",
    createFolder: "폴더 만들기",
    createUnderCurrentFolder: "현재 폴더 아래 만들기",
    createChildFolder: "하위 폴더 만들기",
    rename: "이름 수정",
    deleteFolder: "폴더 삭제",
    folders: "폴더",
    allDocuments: "전체 문서",
    allPapers: "전체 논문",
    libraryRoot: "라이브러리",
    librarySearchPlaceholder: "제목, 저자, 연도, 초록 검색",
    documentsSuffix: "개 문서",
    papersSuffix: "편",
    currentListSelect: "현재 목록 선택",
    selectedSuffix: "개 선택됨",
    moveSelectedPapersPlaceholder: "선택 논문 이동...",
    moveSelectedPapers: "선택 논문 이동",
    delete: "삭제",
    deletePaper: "논문 삭제",
    noPdfInView: "이 보기에는 PDF가 없습니다",
    noPaperInView: "이 보기에는 논문이 없습니다",
    addPdfOrChooseFolder: "PDF를 추가하거나 다른 폴더를 선택하세요.",
    open: "열기",
    bookmark: "북마크",
    removeBookmark: "북마크 해제",
    noAuthors: "저자 정보 없음",
    unknownYear: "연도 -",
    pageSuffix: "쪽",
    emptyReaderTitle: "PDF를 추가하거나 여세요",
    emptyReaderHint: "첫 화면에서 PDF를 추가하고 바로 읽기 작업을 시작할 수 있습니다.",
    openStoredPdf: "저장된 PDF 열기",
    selectedDocumentNeedsLoad: "문서가 선택되었습니다. 로컬 PDF 파일을 불러와 페이지를 렌더링하세요.",
    selectPdf: "PDF 선택",
    highlight: "하이라이트",
    comment: "주석",
    copy: "복사",
    resizeRightPanel: "오른쪽 패널 너비 조절",
    studyTools: "학습 도구",
    highlights: "하이라이트",
    citationCards: "인용카드",
    close: "닫기",
    openPdfForPanels: "PDF를 열면 작업 패널을 사용할 수 있습니다.",
    agentRun: "에이전트 실행",
    refreshResults: "결과 새로고침",
    imageRegion: "이미지 영역",
    suggestedQuestion: "추천 질문",
    suggestedQuestionText: "이 논문의 핵심 기여와 한계를 한국어로 정리해줘.",
    askAnything: "무엇이든 질문하세요.",
    send: "보내기",
    refresh: "새로고침",
    all: "전체",
    quoteSearch: "검색",
    quoteCardsEmpty: "선택 텍스트 설명, 이미지 설명, 인용 이유 결과가 인용카드처럼 쌓입니다.",
    aiResultsEmpty: "AI 에이전트 결과가 여기에 표시됩니다.",
    deleteExplanation: "설명 삭제",
    compactView: "작게 보기",
    fullScreen: "전체화면",
    linkPreview: "링크 미리보기",
    preview: "미리보기",
    sourcePage: "원문 페이지",
    preparingPreview: "미리보기를 준비하는 중입니다...",
    resetPosition: "위치 초기화",
    aiSummary: "AI 요약",
    goToLink: "링크로 이동",
    goToPage: "해당 페이지로 이동",
    externalLinkPreview: "외부 링크 미리보기",
    externalPreviewDescription: "바로 새 탭을 열기 전에 주소를 확인할 수 있도록 미리보기로 표시했습니다.",
    externalPreviewPath: "경로",
    externalPreviewConnectsTo: "로 연결되는 외부 링크입니다.",
    changeTo: "색상 변경",
    goToHighlight: "하이라이트로 이동",
    deleteAllHighlights: "전체 하이라이트 삭제",
    manualAiHighlightsEmpty: "수동/AI 하이라이트가 여기에 표시됩니다.",
    extractReferences: "참고문헌 추출",
    findLinks: "링크 찾기",
    untitledReference: "제목 없는 참고문헌",
    deleteCitation: "인용 삭제",
    openPaper: "논문 열기",
    citationReasonPlaceholder: "인용 이유",
    reason: "이유",
    extractReferencesEmpty: "참고문헌을 추출하면 인용 카드가 만들어집니다.",
    markdownNotes: "Markdown 주석",
    saving: "저장 중...",
    saveNote: "주석 저장",
    unsavedChanges: "저장되지 않은 변경",
    saved: "저장됨",
    saveFailed: "저장 실패",
    extractedTextPreview: "추출 텍스트 미리보기",
    renderPagesToExtract: "페이지를 렌더링하면 선택 가능한 텍스트가 추출됩니다.",
    title: "제목",
    authors: "저자",
    year: "연도",
    abstract: "초록",
    folder: "폴더",
    jsonExport: "JSON 내보내기",
    zipExport: "Zip 내보내기",
    outline: "목차",
    searchHits: "검색 결과",
    noActiveSearchHits: "활성 검색 결과가 없습니다.",
    installed: "설치됨",
    notInstalled: "미설치",
    unknown: "확인 불가",
    claudeMissingHelp: "Claude Code CLI를 설치하거나 CLAUDE_CODE_BIN/CLAUDE_BIN 경로를 설정하세요.",
    claudeMissingSuffix: " (미설치)",
    browserPreviewStatus: "브라우저 프리뷰에서는 CLI 설치 상태를 확인할 수 없습니다. 데스크톱 앱에서는 실제 CLI 경로를 확인합니다.",
    folderNamePrompt: "폴더 이름",
    childFolderNamePrompt: "새 폴더 이름",
    commentPrompt: "주석",
    cannotDeleteRootFolder: "라이브러리 최상위 폴더는 삭제할 수 없습니다.",
    noSavedExplanation: "아직 저장된 설명 답변이 없습니다. 에이전트 결과를 가져오면 다시 열 수 있습니다.",
    openSavedExplanation: "저장된 설명 열기",
    previewTargetNotFound: "미리보기할 링크 위치를 찾지 못했습니다.",
    referencePreviewNotFound: "이 참조의 정확한 미리보기 위치를 찾지 못했습니다.",
    invalidExternalUrl: "외부 링크 주소가 올바르지 않아 열지 않았습니다.",
    noteSaved: "노트를 저장했습니다.",
    noteDeleted: "노트를 삭제했습니다.",
    deleteNote: "노트 삭제",
    wordMeanings: "단어 뜻",
    buildWordMeanings: "단어 뜻 만들기",
    adjustWordMeaning: "뜻 수정",
    wordMeaningLookupOn: "단어 뜻 보기 켜짐",
    wordMeaningLookupOff: "단어 뜻 보기 꺼짐",
    wordMeaningLoading: "한국어 뜻을 불러오는 중...",
    wordMeaningNone: "저장된 한국어 뜻이 없습니다.",
    wordMeaningNoText: "추출된 단어가 없습니다.",
    wordMeaningNoMissing: "새로 만들 단어 뜻이 없습니다.",
    wordMeaningAdjustQueued: "단어 뜻 수정 요청을 대기열에 추가했습니다.",
    reasoningEffort: "추론 강도",
    openDocumentFirst: "먼저 문서를 여세요.",
    openPdfFirst: "먼저 PDF를 여세요.",
    renderPdfFirstForShare: "PDF를 먼저 열어 렌더링한 뒤 공유해 주세요.",
    pdfExportCancelled: "PDF 내보내기가 취소되었습니다.",
    translatedPdfSaved: "번역 PDF 파일을 저장했습니다.",
    translatedPdfDownloaded: "번역 PDF 파일을 다운로드했습니다.",
    copiedSuffix: "복사됨",
    libraryResetDone: "라이브러리와 작업공간 파일을 초기화했습니다.",
    dropPdfsOverlay: "PDF를 놓으면 라이브러리에 추가됩니다",
    dismissMessage: "메시지 닫기",
    regionSizeLabel: "영역",
    dragRegionPrompt: "그림, 표, 수식 영역을 드래그하세요.",
    dropOrChoosePdf: "PDF 파일을 끌어오거나 선택하세요.",
    regionSelectionCancelled: "영역 선택이 취소되었습니다.",
    imageExplanationButtonSaved: "이미지 설명 버튼을 선택한 영역 오른쪽에 저장했습니다.",
    explanationButtonSaved: "설명 버튼을 선택한 줄 오른쪽에 저장했습니다.",
    taskStartedPrefix: "에이전트 시작",
    taskQueuedSuffix: "대기열에 추가했습니다. 에이전트를 실행해 처리하세요.",
    taskCompletedPrefix: "완료",
    noPendingAgentTasks: "대기 중인 에이전트 작업이 없습니다.",
    agentInboxChecked: "에이전트 inbox를 확인했습니다.",
    noAgentWorkerStarted: "시작된 에이전트 작업자가 없습니다.",
    receivedAgentResultsSuffix: "개 에이전트 결과를 받았습니다.",
    highlightsAddedSuffix: "개 AI 하이라이트를 추가했습니다.",
    noExtractableTextCurrentPage: "현재 페이지에서 아직 추출 가능한 텍스트가 없습니다.",
    autoHighlightAlreadyQueued: "현재 페이지는 이미 자동 하이라이트 작업이 대기 중이거나 저장되어 있습니다.",
    queuedAutoHighlightCurrentPage: "현재 페이지 AI 하이라이트 작업을 대기열에 추가했습니다.",
    highlightedLocalCandidatesSuffix: "개 로컬 후보를 현재 페이지에 하이라이트했습니다.",
    citationCardsExtractedSuffix: "개 인용 카드를 추출했습니다.",
    noReferencesFoundYet: "아직 참고문헌을 찾지 못했습니다.",
    noCitationsForLinks: "링크를 찾을 인용 문헌이 없습니다.",
    citationLinksConnectedSuffix: "개 인용 논문 링크를 연결했습니다.",
    deletedExplanation: "설명을 삭제했습니다.",
    noHighlightsToDelete: "삭제할 하이라이트가 없습니다.",
    autoHighlightTurnedOff: "자동 하이라이트가 꺼졌습니다.",
    deleteAllHighlightsConfirm: "이 문서의 모든 하이라이트를 삭제할까요?",
    deletedHighlightsSuffix: "개 하이라이트를 삭제했습니다.",
    deleteFolderConfirm: "이 폴더와 하위 폴더를 삭제할까요? 포함된 논문은 다음 폴더로 이동됩니다:",
    deleteDocumentsConfirm: "선택한 논문을 라이브러리에서 삭제할까요?",
    zipExportWrittenPrefix: "Zip 내보내기 저장 위치",
    pdfSavedPrefix: "PDF 저장 위치",
    libraryResetConfirm: "라이브러리 전체를 삭제할까요?\n\n가져온 PDF, 추출 텍스트, 하이라이트, 주석, 노트, AI 결과, 인용 카드, 에이전트 대기/로그 파일을 삭제합니다. 원본 외부 파일은 건드리지 않습니다.",
    libraryResetSkippedPrefix: "라이브러리를 초기화했습니다. 앱 작업공간 밖이라 건너뛴 경로:",
    openPdfErrorPrefix: "PDF 열기 실패",
    importFailedPrefix: "가져오기 실패",
    aiTaskFailedPrefix: "AI 작업 실패",
    previewFailedPrefix: "미리보기 생성 실패",
    shareFileFailedPrefix: "파일 공유 실패",
    libraryResetFailedPrefix: "라이브러리 초기화 실패",
    citationLinkFailedPrefix: "인용 논문 링크 연결 실패",
    couldNotSavePageTextPrefix: "페이지 텍스트 저장 실패",
    couldNotDeleteAnnotationPrefix: "주석 삭제 실패",
    couldNotDeleteHighlightsPrefix: "전체 하이라이트 삭제 실패",
    couldNotDeleteExplanationPrefix: "설명 삭제 실패",
  },
  en: {
    add: "Add",
    library: "Library",
    settings: "Settings",
    openOutline: "Open outline",
    closeOutline: "Close outline",
    resizeOutline: "Resize outline",
    gridView: "Grid view",
    outlineView: "Outline view",
    pageGrid: "Page grid",
    documentInfo: "Document info",
    search: "Search",
    searchPrompt: "Enter a search term.",
    zoom: "Zoom",
    zoomOut: "Zoom out",
    zoomIn: "Zoom in",
    page: "Page",
    pages: "pages",
    noDocument: "No document",
    untitledPaper: "Untitled paper",
    aiOutline: "AI outline",
    aiOutlinePending: "AI outline pending",
    autoHighlight: "Auto highlight",
    autoHighlightCompact: "Auto highlight",
    autoHighlightToggle: "Toggle auto highlight",
    autoHighlightCurrentPageOnly: "Even when ON, auto highlight runs only on the current page.",
    autoHighlightCurrentPage: "Highlight current page",
    autoHighlightCurrentPageSetting: "Auto highlight current page only",
    explainImage: "Explain image",
    imageExplanation: "Image explanation",
    autoTranslate: "Auto translate",
    translatePage: "Translate page",
    translationPanel: "Translation",
    openTranslationPanel: "Open translation panel",
    closeTranslationPanel: "Close translation panel",
    shareTranslatedPdf: "Share translated PDF",
    addPdf: "Add PDF",
    more: "More",
    panel: "Panel",
    working: "Working",
    settingsTitle: "Settings",
    settingsSubtitle: "Manage UI language, translation language, AI agents, and display preferences.",
    uiLanguage: "UI language",
    translationLanguage: "Translation language",
    theme: "Theme",
    fontSize: "Font size",
    mathDelimiter: "Math delimiter",
    aiProvider: "AI provider",
    model: "Model",
    providerDefault: "Provider default",
    bridgePath: "Agent queue path",
    customPrompt: "Additional prompt",
    runtimeHint: "AI tasks are handled through outbox/inbox JSON queues, with Codex CLI or Claude Code doing the local work.",
    resetTitle: "Delete entire library",
    resetDescription: "Delete imported PDFs, extracted text, highlights, comments, notes, AI results, citation cards, and agent logs.",
    resetAction: "Delete entire library",
    auto: "Auto",
    refreshTranslation: "Refresh translation",
    emptyTranslation: "Reading PDF text. Translation will be requested automatically once sentences are extracted.",
    translationPending: "Fetching translation...",
    translationMissing: "No translation yet. Press refresh to request sentence-level translation.",
    agentPending: "Waiting for agent response",
    keywordsDict: "Keyword dictionary",
    threeLineSummary: "3-line summary",
    summary: "Summary",
    keywordsEmpty: "When AI results arrive, key terms will be organized here automatically.",
    threeLineEmpty: "Run a 3-line summary and it will appear here.",
    summaryEmpty: "Summaries and question answers will appear here.",
    explain: "Explain",
    translate: "Translate",
    askAi: "Ask AI",
    citationReason: "Citation reason",
    linkSummary: "Link summary",
    documentOutline: "Document outline",
    paperRecommendations: "Paper recommendations",
    text: "Text",
    image: "Image",
    url: "URL",
    table: "Table",
    formula: "Formula",
    activity: "Activity",
    citations: "Citations",
    notes: "Notes",
    info: "Info",
    aiPendingAnswer: "Fetching the agent answer.",
    noAnswerContent: "No answer content to display.",
    pageTranslationFallback: "Render this page's text and run auto translation to show the translation here.",
    translationQueued: "Translation pending.",
    translationMissingSaved: "No saved translation yet.",
    shareTruncated: "Some sentences may be clipped because the translation is long.",
    noSentencesOnPage: "No extracted sentences on this page.",
    addPdfDrop: "Click or drag PDFs onto this screen.",
    addPdfToSelectedFolder: "Add papers to the selected folder.",
    newFolder: "New folder",
    createFolder: "Create folder",
    createUnderCurrentFolder: "Create under current folder",
    createChildFolder: "Create child folder",
    rename: "Rename",
    deleteFolder: "Delete folder",
    folders: "Folders",
    allDocuments: "All documents",
    allPapers: "All papers",
    libraryRoot: "Library",
    librarySearchPlaceholder: "Search title, author, year, abstract",
    documentsSuffix: "documents",
    papersSuffix: "papers",
    currentListSelect: "Select current list",
    selectedSuffix: "selected",
    moveSelectedPapersPlaceholder: "Move selected papers...",
    moveSelectedPapers: "Move selected papers",
    delete: "Delete",
    deletePaper: "Delete paper",
    noPdfInView: "No PDFs in this view",
    noPaperInView: "No papers in this view",
    addPdfOrChooseFolder: "Add a PDF or choose another folder.",
    open: "Open",
    bookmark: "Bookmark",
    removeBookmark: "Remove bookmark",
    noAuthors: "No author information",
    unknownYear: "Year -",
    pageSuffix: "p.",
    emptyReaderTitle: "Add or open a PDF",
    emptyReaderHint: "Add a PDF from the first screen and start reading right away.",
    openStoredPdf: "Open stored PDF",
    selectedDocumentNeedsLoad: "The document is selected. Load its local PDF file to render pages.",
    selectPdf: "Select PDF",
    highlight: "Highlight",
    comment: "Comment",
    copy: "Copy",
    resizeRightPanel: "Resize right panel",
    studyTools: "Study tools",
    highlights: "Highlights",
    citationCards: "Citation cards",
    close: "Close",
    openPdfForPanels: "Open a PDF to use the working panels.",
    agentRun: "Run agent",
    refreshResults: "Refresh results",
    imageRegion: "Image region",
    suggestedQuestion: "Suggested question",
    suggestedQuestionText: "Summarize this paper's key contributions and limitations in English.",
    askAnything: "Ask anything.",
    send: "Send",
    refresh: "Refresh",
    all: "All",
    quoteSearch: "Search",
    quoteCardsEmpty: "Text explanations, image explanations, and citation reasons will stack here as quote cards.",
    aiResultsEmpty: "AI agent results will appear here.",
    deleteExplanation: "Delete explanation",
    compactView: "Compact view",
    fullScreen: "Full screen",
    linkPreview: "Link preview",
    preview: "Preview",
    sourcePage: "Source page",
    preparingPreview: "Preparing preview...",
    resetPosition: "Reset position",
    aiSummary: "AI summary",
    goToLink: "Go to link",
    goToPage: "Go to page",
    externalLinkPreview: "External link preview",
    externalPreviewDescription: "Previewing this address before opening it in a new tab.",
    externalPreviewPath: "Path",
    externalPreviewConnectsTo: "is an external link.",
    changeTo: "Change to",
    goToHighlight: "Go to highlight",
    deleteAllHighlights: "Delete all highlights",
    manualAiHighlightsEmpty: "Manual and AI highlights appear here.",
    extractReferences: "Extract references",
    findLinks: "Find links",
    untitledReference: "Untitled reference",
    deleteCitation: "Delete citation",
    openPaper: "Open paper",
    citationReasonPlaceholder: "Citation reason",
    reason: "Reason",
    extractReferencesEmpty: "Extract references to create citation cards.",
    markdownNotes: "Markdown notes",
    saving: "Saving...",
    saveNote: "Save note",
    unsavedChanges: "Unsaved changes",
    saved: "Saved",
    saveFailed: "Save failed",
    extractedTextPreview: "Extracted text preview",
    renderPagesToExtract: "Render pages to extract selectable text.",
    title: "Title",
    authors: "Authors",
    year: "Year",
    abstract: "Abstract",
    folder: "Folder",
    jsonExport: "JSON export",
    zipExport: "Zip export",
    outline: "Outline",
    searchHits: "Search hits",
    noActiveSearchHits: "No active search hits.",
    installed: "Installed",
    notInstalled: "Not installed",
    unknown: "Unknown",
    claudeMissingHelp: "Install Claude Code CLI or set CLAUDE_CODE_BIN/CLAUDE_BIN.",
    claudeMissingSuffix: " (not installed)",
    browserPreviewStatus: "CLI install status cannot be checked in browser preview. The desktop app checks the actual CLI path.",
    folderNamePrompt: "Folder name",
    childFolderNamePrompt: "New folder name",
    commentPrompt: "Comment",
    cannotDeleteRootFolder: "The library root folder cannot be deleted.",
    noSavedExplanation: "No saved explanation yet. Fetch agent results and try again.",
    openSavedExplanation: "Open saved explanation",
    previewTargetNotFound: "Could not find the link location to preview.",
    referencePreviewNotFound: "Could not find the exact preview location for this reference.",
    invalidExternalUrl: "The external link address is invalid and was not opened.",
    noteSaved: "Note saved.",
    noteDeleted: "Note deleted.",
    deleteNote: "Delete note",
    wordMeanings: "Word meanings",
    buildWordMeanings: "Build word meanings",
    adjustWordMeaning: "Adjust meaning",
    wordMeaningLookupOn: "Word meaning popup on",
    wordMeaningLookupOff: "Word meaning popup off",
    wordMeaningLoading: "Loading Korean meaning...",
    wordMeaningNone: "No saved Korean meaning.",
    wordMeaningNoText: "No extracted words yet.",
    wordMeaningNoMissing: "No missing word meanings.",
    wordMeaningAdjustQueued: "Queued word meaning adjustment.",
    reasoningEffort: "Reasoning effort",
    openDocumentFirst: "Open a document first.",
    openPdfFirst: "Open a PDF first.",
    renderPdfFirstForShare: "Open and render the PDF before sharing.",
    pdfExportCancelled: "PDF export cancelled.",
    translatedPdfSaved: "Translated PDF file saved.",
    translatedPdfDownloaded: "Translated PDF file downloaded.",
    copiedSuffix: "copied",
    libraryResetDone: "Library and workspace files were reset.",
    dropPdfsOverlay: "Drop PDFs to add them to the library",
    dismissMessage: "Dismiss message",
    regionSizeLabel: "Region",
    dragRegionPrompt: "Drag over a figure, table, or formula region.",
    dropOrChoosePdf: "Drop or choose a PDF file.",
    regionSelectionCancelled: "Region selection cancelled.",
    imageExplanationButtonSaved: "Saved the image explanation button beside the selected region.",
    explanationButtonSaved: "Saved the explanation button beside the selected line.",
    taskStartedPrefix: "Started agent for",
    taskQueuedSuffix: "queued. Run the agent to process it.",
    taskCompletedPrefix: "Completed",
    noPendingAgentTasks: "No pending agent tasks.",
    agentInboxChecked: "Agent inbox checked.",
    noAgentWorkerStarted: "No agent worker started.",
    receivedAgentResultsSuffix: "agent result(s) received.",
    highlightsAddedSuffix: "AI highlight(s) added.",
    noExtractableTextCurrentPage: "No extractable text is available on the current page yet.",
    autoHighlightAlreadyQueued: "Current page already has auto-highlight work queued or saved.",
    queuedAutoHighlightCurrentPage: "Queued AI highlighting for the current page.",
    highlightedLocalCandidatesSuffix: "local candidate(s) highlighted on the current page.",
    citationCardsExtractedSuffix: "citation card(s) extracted.",
    noReferencesFoundYet: "No references found yet.",
    noCitationsForLinks: "No citation references available for link lookup.",
    citationLinksConnectedSuffix: "citation link(s) connected.",
    deletedExplanation: "Deleted explanation.",
    noHighlightsToDelete: "No highlights to delete.",
    autoHighlightTurnedOff: "Auto highlight is off.",
    deleteAllHighlightsConfirm: "Delete all highlights in this document?",
    deletedHighlightsSuffix: "highlight(s) deleted.",
    deleteFolderConfirm: "Delete this folder and its child folders? Included papers will be moved to:",
    deleteDocumentsConfirm: "Delete the selected papers from the library?",
    zipExportWrittenPrefix: "Zip export written to",
    pdfSavedPrefix: "PDF saved to",
    libraryResetConfirm: "Delete the entire library?\n\nThis deletes imported PDFs, extracted text, highlights, comments, notes, AI results, citation cards, and queued/logged agent files. Original external files are not touched.",
    libraryResetSkippedPrefix: "Library reset completed. Skipped paths outside the app workspace:",
    openPdfErrorPrefix: "Could not open PDF",
    importFailedPrefix: "Import failed",
    aiTaskFailedPrefix: "AI task failed",
    previewFailedPrefix: "Preview failed",
    shareFileFailedPrefix: "Share file failed",
    libraryResetFailedPrefix: "Library reset failed",
    citationLinkFailedPrefix: "Citation link failed",
    couldNotSavePageTextPrefix: "Could not save page text",
    couldNotDeleteAnnotationPrefix: "Could not delete annotation",
    couldNotDeleteHighlightsPrefix: "Could not delete all highlights",
    couldNotDeleteExplanationPrefix: "Could not delete explanation",
  },
};

export const UiStringsContext = createContext<UiStrings>(uiStrings.ko);

export function useUiStrings() {
  return useContext(UiStringsContext);
}

export const translationLanguageOptions = [
  { value: "ko", ko: "한국어", en: "Korean", prompt: "Korean" },
  { value: "en", ko: "영어", en: "English", prompt: "English" },
  { value: "ja", ko: "일본어", en: "Japanese", prompt: "Japanese" },
  { value: "zh-Hans", ko: "중국어 간체", en: "Chinese (Simplified)", prompt: "Simplified Chinese" },
  { value: "zh-Hant", ko: "중국어 번체", en: "Chinese (Traditional)", prompt: "Traditional Chinese" },
  { value: "ru", ko: "러시아어", en: "Russian", prompt: "Russian" },
  { value: "es", ko: "스페인어", en: "Spanish", prompt: "Spanish" },
  { value: "fr", ko: "프랑스어", en: "French", prompt: "French" },
  { value: "de", ko: "독일어", en: "German", prompt: "German" },
  { value: "pt", ko: "포르투갈어", en: "Portuguese", prompt: "Portuguese" },
  { value: "vi", ko: "베트남어", en: "Vietnamese", prompt: "Vietnamese" },
  { value: "th", ko: "태국어", en: "Thai", prompt: "Thai" },
  { value: "id", ko: "인도네시아어", en: "Indonesian", prompt: "Indonesian" },
  { value: "ar", ko: "아랍어", en: "Arabic", prompt: "Arabic" },
];

export function uiLanguageFromSettings(settings: Record<string, string>): UiLanguage {
  return settings.uiLanguage === "en" ? "en" : "ko";
}

export function translationLanguageOption(value: string | undefined) {
  return translationLanguageOptions.find((option) => option.value === value) ?? translationLanguageOptions[0];
}

export function translationLanguageNameFromSettings(settings: Record<string, string>) {
  return translationLanguageOption(settings.translationLanguage).prompt;
}

export function translationLanguageLabel(value: string | undefined, uiLanguage: UiLanguage) {
  const option = translationLanguageOption(value);
  return uiLanguage === "ko" ? option.ko : option.en;
}

